#!/usr/bin/env python3
"""Auto-generated by agentcomms-bridge — reads trigger file. ZERO network calls."""
import json, os, sys

TRIGGER = "/tmp/satori-engine/.agentcomms-trigger"

if not os.path.exists(TRIGGER):
    sys.exit(0)

try:
    with open(TRIGGER) as f:
        task = json.load(f)
    os.unlink(TRIGGER)
    sender = task.get("sender", "coordinator")
    body = task.get("body", "")
    if body:
        print(f"[BRIDGE TASK from {sender}] {body}")
except Exception:
    sys.exit(0)
